export const CLASSES = {
  Calendar: "Calendar",
  Wrapper: "Calendar-Wrapper",
  Calendar_mod_dates: "Calendar_mod_dates",
  Calendar_mod_months: "Calendar_mod_months",
  Calendar_mod_years: "Calendar_mod_years",
  Header: "Calendar-Header",
  PrevButton: "Calendar-PrevButton",
  NextButton: "Calendar-NextButton",
  Title: "Calendar-Title",
  TitleMonth: "Calendar-TitleMonth",
  TitleYear: "Calendar-TitleYear",
  TitleRangeYears: "Calendar-TitleRangeYears",
  Body: "Calendar-Body",
  View: "Calendar-View",
  View_type_dates: "Calendar-View_type_dates",
  View_type_months: "Calendar-View_type_months",
  View_type_years: "Calendar-View_type_years",
  ViewRow: "Calendar-ViewRow",
  ViewItem: "Calendar-ViewItem",
  ViewItem_disable: "Calendar-ViewItem_disable",
  ViewItem_today: "Calendar-ViewItem_today",
  ViewItem_status_active: "Calendar-ViewItem_status_active",
  Toolbar: "Calendar-Toolbar",
  ToolbarButton: "Calendar-ToolbarButton",
  TodayButton: "Calendar-TodayButton",
  ClearActiveDatesButton: "Calendar-ClearActiveDatesButton",
  WeekDays: "Calendar-WeekDays",
  WeekDay: "Calendar-WeekDay",
  Button: "Calendar-Button",
  Icon: "Calendar-Icon"
};

export const EVENTS = {
  ADD_DATE: "addDate",
  REMOVE_DATE: "removeDate",
  CHANGE_MONTH: "changeMonth",
  CHANGE_YEAR: "changeYear",
  CHANGE_DATA: "changeData",
  CLEAR_ACTIVE_DATES: "clearActiveDates"
} as const;
